"""
Utility functions shared across the NbSi-SHAP-AL pipeline.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib
matplotlib.use("Agg")  # non-interactive backend for server/CI environments

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

from src.active_learning import ALResult

# Default output directory for figures
RESULTS_DIR = Path(__file__).parent.parent / "results"


# ---------------------------------------------------------------------------
# Data helpers
# ---------------------------------------------------------------------------

def load_data(path: str | Path) -> tuple[pd.DataFrame, pd.Series]:
    """Load the Nb-Si dataset CSV and return (X, y).

    Parameters
    ----------
    path:
        Path to the CSV file generated by ``data/generate_data.py``.

    Returns
    -------
    X : pd.DataFrame
        Feature matrix (all element columns).
    y : pd.Series
        Target vector (KIC column).
    """
    df = pd.read_csv(path)
    if "KIC" not in df.columns:
        raise ValueError(f"Expected 'KIC' column in {path}.")
    y = df["KIC"].copy()
    X = df.drop(columns=["KIC"])
    return X, y


def split_initial_pool(
    n_samples: int,
    n_initial: int,
    random_state: int = 0,
) -> list[int]:
    """Randomly select *n_initial* indices as the initial labelled pool.

    The remaining indices form the unlabelled candidate pool, which the
    :class:`~src.active_learning.ActiveLearner` computes internally by
    taking the complement of the labelled set.

    Parameters
    ----------
    n_samples:
        Total number of samples.
    n_initial:
        Number of samples to label initially.
    random_state:
        NumPy random seed.

    Returns
    -------
    initial_indices : list[int]
        Indices of the initially labelled samples.
    """
    rng = np.random.default_rng(random_state)
    all_idx = np.arange(n_samples)
    rng.shuffle(all_idx)
    return list(all_idx[:n_initial])


# ---------------------------------------------------------------------------
# Plotting helpers
# ---------------------------------------------------------------------------

def plot_learning_curve(result: ALResult, save_path: Path | None = None) -> None:
    """Plot RMSE and R² vs. number of labelled samples.

    Parameters
    ----------
    result:
        Output of :meth:`ActiveLearner.run`.
    save_path:
        If given, save the figure to this path.
    """
    df = result.to_dataframe()
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    axes[0].plot(df["n_labelled"], df["rmse"], marker="o", linewidth=2, color="steelblue")
    axes[0].set_xlabel("Number of labelled samples")
    axes[0].set_ylabel("RMSE (MPa·m$^{0.5}$)")
    axes[0].set_title("Prediction error vs. labelled pool size")
    axes[0].grid(True, alpha=0.3)

    axes[1].plot(df["n_labelled"], df["r2"], marker="s", linewidth=2, color="darkorange")
    axes[1].set_xlabel("Number of labelled samples")
    axes[1].set_ylabel("R²")
    axes[1].set_title("R² vs. labelled pool size")
    axes[1].grid(True, alpha=0.3)
    axes[1].set_ylim([0, 1.05])

    fig.suptitle("Active Learning – model improvement over iterations", fontsize=14)
    fig.tight_layout()
    _save_or_show(fig, save_path)


def plot_kic_discovery(result: ALResult, save_path: Path | None = None) -> None:
    """Plot best KIC discovered vs. number of labelled samples.

    Parameters
    ----------
    result:
        Output of :meth:`ActiveLearner.run`.
    save_path:
        If given, save the figure to this path.
    """
    df = result.to_dataframe()
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(
        df["n_labelled"],
        df["best_kic"],
        marker="^",
        linewidth=2,
        color="seagreen",
        label="Best KIC discovered",
    )
    ax.scatter(
        df["n_labelled"],
        df["selected_kic"],
        color="crimson",
        zorder=3,
        s=40,
        label="Selected sample KIC",
        alpha=0.7,
    )
    ax.set_xlabel("Number of labelled samples")
    ax.set_ylabel("KIC (MPa·m$^{0.5}$)")
    ax.set_title("Discovery of high-toughness Nb-Si alloys via active learning")
    ax.legend()
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    _save_or_show(fig, save_path)


def plot_shap_importance_heatmap(
    result: ALResult, save_path: Path | None = None
) -> None:
    """Plot a heatmap of mean |SHAP| per feature over AL iterations.

    Parameters
    ----------
    result:
        Output of :meth:`ActiveLearner.run`.
    save_path:
        If given, save the figure to this path.
    """
    importance_df = result.shap_importance_over_time()
    fig, ax = plt.subplots(figsize=(10, 6))
    sns.heatmap(
        importance_df.T,
        ax=ax,
        cmap="YlOrRd",
        cbar_kws={"label": "Mean |SHAP| value"},
        linewidths=0.3,
    )
    ax.set_xlabel("AL iteration")
    ax.set_ylabel("Feature")
    ax.set_title("Dynamic SHAP feature importance over active learning iterations")
    fig.tight_layout()
    _save_or_show(fig, save_path)


def plot_final_shap_bar(result: ALResult, save_path: Path | None = None) -> None:
    """Bar chart of mean |SHAP| values at the final AL iteration.

    Parameters
    ----------
    result:
        Output of :meth:`ActiveLearner.run`.
    save_path:
        If given, save the figure to this path.
    """
    last = result.history[-1].mean_abs_shap.sort_values(ascending=True)
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.barh(last.index, last.values, color="steelblue", edgecolor="black", alpha=0.8)
    ax.set_xlabel("Mean |SHAP| value")
    ax.set_title("Final SHAP feature importance (mean |SHAP| over candidates)")
    ax.grid(True, axis="x", alpha=0.3)
    fig.tight_layout()
    _save_or_show(fig, save_path)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _save_or_show(fig: plt.Figure, save_path: Path | None) -> None:
    if save_path is not None:
        save_path.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(save_path, dpi=150, bbox_inches="tight")
        print(f"  Figure saved → {save_path}")
    plt.close(fig)
